/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Insurers
         * @description 2-Phase Retrieval 비교 검색
         *
         *     - **compare_axis**: 가입설계서/상품요약서/사업방법서에서 coverage_code 기반 근거 수집
         *     - **policy_axis**: 약관에서 키워드 기반 조문 근거 수집 (A2 정책)
         */
        post: operations["compare_insurers_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/page/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Page
         * @description PDF 문서의 특정 페이지를 PNG 이미지로 반환
         *
         *     - **document_id**: 문서 ID (DB에서 조회)
         *     - **page**: 페이지 번호 (1-based)
         *     - **scale**: 이미지 스케일 (1.0 ~ 4.0, 기본 2.0)
         *
         *     Returns:
         *         PNG 이미지
         *
         *     Errors:
         *         - 404: 문서 없음 또는 페이지 범위 초과
         *         - 500: 렌더링 실패
         */
        get: operations["get_document_page_documents__document_id__page__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Info
         * @description 문서 정보 조회 (페이지 수 등)
         *
         *     Returns:
         *         - page_count: 총 페이지 수
         *         - source_path: 파일 경로
         */
        get: operations["get_document_info_documents__document_id__info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/page/{page}/spans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Page Spans
         * @description PDF 페이지에서 텍스트 하이라이트 영역 찾기
         *
         *     - **document_id**: 문서 ID
         *     - **page**: 페이지 번호 (1-based)
         *     - **q**: 검색할 텍스트 (최대 200자)
         *     - **max_hits**: 최대 반환 개수 (기본 5, 최대 20)
         *
         *     Returns:
         *         hits: 매칭된 영역 리스트 (bbox, score, text)
         *
         *     Note:
         *         - 매칭 실패 시 hits=[] 반환 (200 OK)
         *         - bbox는 PDF 좌표계 기준 (스케일 미적용)
         */
        get: operations["get_page_spans_documents__document_id__page__page__spans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 헬스 체크
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description API 정보
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AmountInfoResponse
         * @description 금액 정보
         */
        AmountInfoResponse: {
            /** Amount Value */
            amount_value: number | null;
            /** Amount Text */
            amount_text: string | null;
            /** Unit */
            unit: string | null;
            /** Confidence */
            confidence: string;
            /** Method */
            method: string;
        };
        /**
         * CompareAxisItemResponse
         * @description Compare Axis 결과 항목
         */
        CompareAxisItemResponse: {
            /** Insurer Code */
            insurer_code: string;
            /** Coverage Code */
            coverage_code: string;
            /** Coverage Name */
            coverage_name: string | null;
            /** Doc Type Counts */
            doc_type_counts: {
                [key: string]: number;
            };
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
        };
        /**
         * CompareRequest
         * @description 비교 검색 요청
         * @example {
         *       "age": 35,
         *       "compare_doc_types": [
         *         "가입설계서",
         *         "상품요약서",
         *         "사업방법서"
         *       ],
         *       "coverage_codes": [
         *         "A4200_1",
         *         "A4210"
         *       ],
         *       "gender": "M",
         *       "insurers": [
         *         "SAMSUNG",
         *         "MERITZ"
         *       ],
         *       "policy_doc_types": [
         *         "약관"
         *       ],
         *       "policy_keywords": [
         *         "경계성",
         *         "유사암",
         *         "제자리암"
         *       ],
         *       "query": "경계성 종양 암진단비",
         *       "top_k_per_insurer": 10
         *     }
         */
        CompareRequest: {
            /**
             * Insurers
             * @description 비교할 보험사 코드 리스트
             */
            insurers: string[];
            /**
             * Query
             * @description 사용자 질의
             */
            query: string;
            /**
             * Coverage Codes
             * @description 필터할 coverage_code 리스트
             */
            coverage_codes?: string[] | null;
            /**
             * Top K Per Insurer
             * @description 보험사별 최대 결과 수
             * @default 10
             */
            top_k_per_insurer: number;
            /**
             * Compare Doc Types
             * @description Compare Axis 대상 doc_type
             * @default [
             *       "가입설계서",
             *       "상품요약서",
             *       "사업방법서"
             *     ]
             */
            compare_doc_types: string[];
            /**
             * Policy Doc Types
             * @description Policy Axis 대상 doc_type
             * @default [
             *       "약관"
             *     ]
             */
            policy_doc_types: string[];
            /**
             * Policy Keywords
             * @description 약관 검색 키워드
             * @default []
             */
            policy_keywords: string[];
            /**
             * Age
             * @description 피보험자 나이 (plan 자동 선택용)
             */
            age?: number | null;
            /**
             * Gender
             * @description 피보험자 성별 (M/F)
             */
            gender?: ("M" | "F") | null;
        };
        /**
         * CompareResponseModel
         * @description 비교 검색 응답
         */
        CompareResponseModel: {
            /** Compare Axis */
            compare_axis: components["schemas"]["CompareAxisItemResponse"][];
            /** Policy Axis */
            policy_axis: components["schemas"]["PolicyAxisItemResponse"][];
            /** Coverage Compare Result */
            coverage_compare_result: components["schemas"]["CoverageCompareRowResponse"][];
            /** Diff Summary */
            diff_summary: components["schemas"]["DiffSummaryItemResponse"][];
            /** Debug */
            debug: {
                [key: string]: unknown;
            };
        };
        /**
         * ConditionInfoResponse
         * @description 지급조건 정보
         */
        ConditionInfoResponse: {
            /** Snippet */
            snippet: string | null;
            /** Matched Terms */
            matched_terms: string[];
        };
        /**
         * CoverageCompareRowResponse
         * @description 비교표 행: coverage_code 기준
         */
        CoverageCompareRowResponse: {
            /** Coverage Code */
            coverage_code: string;
            /** Coverage Name */
            coverage_name: string | null;
            /** Insurers */
            insurers: components["schemas"]["InsurerCompareCellResponse"][];
        };
        /**
         * DiffBulletResponse
         * @description 차이점 문장
         */
        DiffBulletResponse: {
            /** Text */
            text: string;
            /** Evidence Refs */
            evidence_refs: components["schemas"]["EvidenceRefResponse"][];
        };
        /**
         * DiffSummaryItemResponse
         * @description coverage_code별 차이점 요약
         */
        DiffSummaryItemResponse: {
            /** Coverage Code */
            coverage_code: string;
            /** Coverage Name */
            coverage_name: string | null;
            /** Bullets */
            bullets: components["schemas"]["DiffBulletResponse"][];
        };
        /**
         * EvidenceRefResponse
         * @description 근거 참조
         */
        EvidenceRefResponse: {
            /** Insurer Code */
            insurer_code: string;
            /** Document Id */
            document_id: number;
            /** Page Start */
            page_start: number | null;
        };
        /**
         * EvidenceResponse
         * @description 검색 결과 근거
         */
        EvidenceResponse: {
            /** Document Id */
            document_id: number;
            /** Doc Type */
            doc_type: string;
            /** Page Start */
            page_start: number | null;
            /** Preview */
            preview: string;
            /** Score */
            score: number;
            amount?: components["schemas"]["AmountInfoResponse"] | null;
            condition_snippet?: components["schemas"]["ConditionInfoResponse"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InsurerCompareCellResponse
         * @description 비교표 셀: 보험사별 결과
         */
        InsurerCompareCellResponse: {
            /** Insurer Code */
            insurer_code: string;
            /** Doc Type Counts */
            doc_type_counts: {
                [key: string]: number;
            };
            /** Best Evidence */
            best_evidence: components["schemas"]["EvidenceResponse"][];
        };
        /**
         * PolicyAxisItemResponse
         * @description Policy Axis 결과 항목
         */
        PolicyAxisItemResponse: {
            /** Insurer Code */
            insurer_code: string;
            /** Keyword */
            keyword: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
        };
        /**
         * SpanHit
         * @description 단일 하이라이트 영역
         */
        SpanHit: {
            /** Bbox */
            bbox: number[];
            /** Score */
            score: number;
            /** Text */
            text: string;
        };
        /**
         * SpansResponse
         * @description 하이라이트 영역 응답
         */
        SpansResponse: {
            /** Document Id */
            document_id: number;
            /** Page */
            page: number;
            /** Hits */
            hits: components["schemas"]["SpanHit"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare_insurers_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponseModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_page_documents__document_id__page__page__get: {
        parameters: {
            query?: {
                /** @description 렌더링 스케일 */
                scale?: number;
            };
            header?: never;
            path: {
                document_id: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_info_documents__document_id__info_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_page_spans_documents__document_id__page__page__spans_get: {
        parameters: {
            query: {
                /** @description 하이라이트할 텍스트 */
                q: string;
                /** @description 최대 반환 개수 */
                max_hits?: number;
            };
            header?: never;
            path: {
                document_id: number;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpansResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
